### PR TITLE
Browserify the tablist

### PR DESCRIPTION
**Pull request by ehunter-usgs**
EQH-2987

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
- remove ImageList

- spec/TabListTest doesn't need to be bundled
- for TabList bundle, change browserify config to end up like this (still use variables...).  This makes the bundle export something that can be ```require```d after including the script.
```
browserify['tablist/TabList'] = {
  src:[],
  dest: '.build/src/tablist/TabList.js',
  options: {
    alias: ['src/tablist/TabList.js:tablist/TabList']
  }
};
```

- index (tests) can continue being bundled
- example, usability can make TabList external and reference the TabList bundle:
```
browserify['example'] = {
  src: 'test/example.js',
  dest: '.build/test/example.js',
  options: {
    external: 'tablist/TabList'
  }
}
```

```
  <script src="tablist/TabList.js"></script>
  <script src="example.js"></script>
```

- Use separate directory and mount for examples (examples mount on port 8000, tests mount on port 8001, dist mounts on port 8002).

**Comment by jmfee-usgs** [comment]
Since the example only requires a single file, it does not have to be browserified but it still can.

**Comment by jmfee-usgs** [comment]
browserify
- make bundle destination `hazdev-tablist.js` instead of tablist/TabList.js

cssmin
- create 'hazdev-tablist.css' as part of dist process, add replace task to replace css path in examples for dist.

examples
- include script element for 'hazdev-tablist.js' before the example javascript

connect/copy
- Mount the node_modules folder for the test port and you can eliminate copy:mocha.

tablist
- can _this.tabs be a private variable

**Comment by emartinez-usgs** [comment]
- The example.html file should link to the usability.html file.
- Remove '.tmp' from the config.js
- Rewrite cssmin configuration. Use config for paths.
- I don't think we use grunt-contrib-replace anymore. Remove it if not.
- Simplify uglify configuration since there is only one target.
- No need to run browserify or mocha_phantomjs when example files change. This would have no effect.
- Watch gruntconfig files and run jshint when they change.
- Should only re-browserify the code that changes. I.e. only run browserify:source when source files change, only run browserify:test when test files change.
- span.fade and nav.smooth probably need some scoping in css.
- Pull chai (and sinon?) out of test.js bundle.

**Pull request merged**
